Still Error: undefined is not an object...RNSearchBarManager...

diff --git a/ios/PodFile b/ios/PodFile
--- a/ios/PodFile
+++ b/ios/PodFile
@@ -2,17 +2,35 @@
 
 target 'TradeMuch' do
   source 'https://github.com/CocoaPods/Specs.git'
-  pod 'React', :subspecs => ['Core', 'RCTImage', 'RCTNetwork', 'RCTText', 'RCTWebSocket'], :path => '../node_modules/react-native'
-  pod 'react-native-fbsdkcore', :path => '../node_modules/react-native-fbsdk/iOS/core'
-  pod 'react-native-fbsdklogin', :path => '../node_modules/react-native-fbsdk/iOS/login'
-  pod 'react-native-fbsdkshare', :path => '../node_modules/react-native-fbsdk/iOS/share'
+  pod 'React', :subspecs => [
+    'Core',
+    'RCTImage',
+    'RCTNetwork',
+    'RCTText',
+    'RCTWebSocket'
+  ], :path => '../node_modules/react-native'
+  pod 'react-native-fbsdkcore', :path => '../node_modules/react-native-fbsdkcore'
+  pod 'react-native-fbsdklogin', :path => '../node_modules/react-native-fbsdklogin'
+  pod 'react-native-fbsdkshare', :path => '../node_modules/react-native-fbsdkshare'
   pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'
   pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
 end
 
 # Start the React Native JS packager server when running the project in Xcode.
-# post_install do |installer|
-#   target = installer.pods_project.targets.select{|t| 'React' == t.name}.first
-#   phase = target.new_shell_script_build_phase('Run Script')
-#   phase.shell_script = "if nc -w 5 -z localhost 8081 ; then\n  if ! curl -s \"http://localhost:8081/status\" | grep -q \"packager-status:running\" ; then\n    echo \"Port 8081 already in use, packager is either not running or not running correctly\"\n    exit 2\n  fi\nelse\n  open $SRCROOT/../../node_modules/react-native/packager/launchPackager.command || echo \"Can't start packager automatically\"\nfi"
-# end
+
+start_packager = %q(
+if nc -w 5 -z localhost 8081 ; then
+  if ! curl -s "http://localhost:8081/status" | grep -q "packager-status:running" ; then
+    echo "Port 8081 already in use, packager is either not running or not running correctly"
+    exit 2
+  fi
+else
+  open $SRCROOT/../../node_modules/react-native/packager/launchPackager.command || echo "Can't start packager automatically"
+fi
+)
+
+post_install do |installer|
+  target = installer.pods_project.targets.select{|t| 'React' == t.name}.first
+  phase = target.new_shell_script_build_phase('Run Script')
+  phase.shell_script = start_packager
+end
